#!/usr/bin/env bash

export CONTECO_LABEL="confluent_cc.base - ContEco"
export CONTECO_DESCRIPTION="Confluent Control Center Base image, with configuration changes."

export CONTECO_TYPE="confluent_cc"
export CONTECO_NAME="base"
export CONTECO_TAG="6.0.0"

export CONTECO_BASE="external.confluent_cc:6.0.0"
export CONTECO_BUILD="image-base"

export CONTECO_EXTERNAL_IMAGE_NAME="confluentinc/cp-enterprise-control-center:6.0.0"
